### ISSUE TITLE
"Command \tmpparindent already defined" error using multiple onecolumninline commands

### ISSUE THREAD

**Issue by faragher** [slithy/rpg_module#10]
Using PDFLaTeX (and to my understanding other LaTeX renderers) using more than one \onecolumninline throws the following error because lengths are immutable.

```
! LaTeX Error: Command \tmpparindent already defined.
               Or name \end... illegal, see p.192 of the manual.
```

As a work-around, removing the following from the command and placing them in the main loop functions as intended (for a single formatting style, such as a simple booklet made with this package):

```
\newlength{\tmpparindent}
\newlength{\tmpparskip}
\setlength{\tmpparindent}{\parindent}
\setlength{\tmpparskip}{\parskip}
```

It's possible converting these to variables could prevent this issue, but I'm mostly reporting it for completeness sake or to assist people with a similar error.

Example modified code (field modification, it really should be addressed using variables, which is beyond my skills)

```
% Single-column text

%Removed from below command
\newlength{\tmpparindent}
\newlength{\tmpparskip}
\setlength{\tmpparindent}{\parindent}
\setlength{\tmpparskip}{\parskip}

\newcommand\onecolumninline[1]{%
%Above definitions removed from this location
\twocolumn[{
\setlength{\parindent}{\tmpparindent}
\setlength{\parskip}{\tmpparskip}
\fussy
#1
\vspace{2ex}
}]
}
```

**Comment by slithy** [comment]
Thanks for reporting this and sorry it has taken me so long to address it!

I have just pushed the following fix to main:
```
diff --git a/rpg-module.cls b/rpg-module.cls
index 26e828c..c797f37 100644
--- a/rpg-module.cls
+++ b/rpg-module.cls
@@ -512,9 +512,10 @@
 
 % Single-column text
 
-\newcommand\onecolumninline[1]{%
 \newlength{\tmpparindent}
 \newlength{\tmpparskip}
+
+\newcommand\onecolumninline[1]{%
 \setlength{\tmpparindent}{\parindent}
 \setlength{\tmpparskip}{\parskip}
 \twocolumn[{
```
