### ISSUE TITLE
OGL 1.0a Content

### ISSUE THREAD

**Issue by OmegaRogue** [slithy/rpg_module#11]
Recently, there has been alot going on around the OGL 1.0a, with Wizards of the Coast seemingly trying to revoke it (https://www.opendnd.games/ ). What parts of this are OGL 1.0a, and would it be possible to make an option to disable all OGL content when using this template?

**Comment by slithy** [comment]
Hello and thank you for the question. I have also been reading about the massive IP grab by Hasbro/WotC and share your concerns and that of our wider community.

Of course Hasbro's claims have not been tested in court and there are various legal opinions. Unless they back down under community pressure, we are likely to enter into a period of uncertainty as to whether they can revoke the OGL 1.0a license or not.

In terms of the `rpg_module` LaTeX class, it is of course primarily typesetting and layout which are not elements subject to OGL. `rpg_module` itself is licenced under LPPL (LaTeX Project Public License), which is a free license. See the `LICENSE` file for the details.

The text which you write yourself may or may not be subject to OGL, depending on what you write. You are free to include the OGL license, or not. I provided an option to include the OGL license as a single command to make it easy for people who wanted to do that.

If you use the optional monster stat blocks in your published text, it could be that these require the OGL license. However, the SRD started with D&D v3.5 and the stats provided pre-date this, so I'm not sure. To my knowledge this has never been tested in court and I am not a legal expert, so I'm unable to give you a definitive answer about that.
